<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AssignmentSectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AssignmentSectionRepository extends EntityRepository
{

    function findWithCorrectionDependencies($assignmentId, $correctionId)
    {
        $qb = $this->createQueryBuilder('ds');
        $qb->select('ds', 'cs')
            ->innerJoin('ds.section', 's')
            ->leftJoin('ds.correction_sections', 'cs', 'WITH', 'cs.correction = :correctionId')
            ->where('ds.assignment = :assignmentId')
            ->orderBy('s.order', 'ASC')
            ->setParameters(array(
                'assignmentId' => $assignmentId,
                'correctionId' => $correctionId
            ));
        $query = $qb->getQuery();
        $results = $query->getResult();
        return $results;
    }
}
