<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AssignmentCriteriaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AssignmentCriteriaRepository extends EntityRepository
{
    /**
     * @param integer $assignmentId
     * @param integer $sectionId
     * @return array
     */
    function findFeedbackByAssignmentAndSection($assignmentId, $sectionId)
    {
        // Get comments
        $qb = $this->createQueryBuilder('dc');
        $qb->select('cr.description', 'dc.mark')
            ->innerJoin('dc.criteria', 'cr', 'WITH', 'cr.showMark = true')
            ->where('dc.assignment = :assignment')
            ->andWhere('dc.section = :section')
            ->setParameters(array(
                'section' => $sectionId,
                'assignment' => $assignmentId
            ));
        $query = $qb->getQuery();
        $results = $query->getResult();

        return $results;
    }
}
