<?php

namespace AppBundle\Repository;

/**
 * LogConnectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConnectionLogRepository extends \Doctrine\ORM\EntityRepository
{
}
