<?php

namespace AppBundle\Repository;

/**
 * CorrectionSectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CorrectionSectionRepository extends \Doctrine\ORM\EntityRepository
{
}
