<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CriteriaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CriteriaRepository extends EntityRepository
{
    public function findByEvaluation($evaluationId)
    {
        $qb = $this->createQueryBuilder('c');
        $qb->select('c')
            ->innerJoin('c.section', 's')
            ->where('s.evaluation = :evaluationId')
            ->setParameters(array('evaluationId' => $evaluationId));

        $query = $qb->getQuery();
        $results = $query->getResult();
        return $results;
    }
}
