<?php

namespace AppBundle\Repository;

/**
 * ExampleAssignmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExampleAssignmentRepository extends \Doctrine\ORM\EntityRepository
{
}
