<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * GroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupRepository extends EntityRepository
{

    public function findByEvaluationUsers($evaluationId)
    {
        $stmt = $this->getEntityManager()->getConnection()->prepare("
                SELECT 
                    DISTINCT g.*                    
                FROM groups g
                INNER JOIN user_has_group uhg ON uhg.group_id = g.id
                INNER JOIN user_has_evaluation uhe ON uhe.user_id = uhg.user_id
                WHERE uhe.evaluation_id = :evaluationId
                ORDER BY g.name");
        $stmt->execute([
            'evaluationId' => $evaluationId
        ]);
        return $stmt->fetchAll();
    }

    public function findGroupByUser($id)
    {
        $qb = $this->createQueryBuilder('g');
        $qb->select('g')
            ->innerJoin('g.users', 'u')
            ->where('u.id = :userId')
            ->setParameters(array(
                'userId' => $id
            ));
        $query = $qb->getQuery();
        $results = $query->getResult();
        return $results;
    }
}
