<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * LessonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LessonRepository extends EntityRepository
{
    public function findByUser($userId)
    {
        $qb = $this->createQueryBuilder('c');
        $qb->select('c')
            ->innerJoin('c.users', 'u')
            ->where('u.id = :userId')
            ->orderBy('c.name', 'ASC')
            ->setParameters(array(
                'userId' => $userId
            ));
        $query = $qb->getQuery();
        $results = $query->getResult();
        return $results;
    }
}
