<?php

namespace AppBundle\Repository;

/**
 * MarkModeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MarkModeRepository extends \Doctrine\ORM\EntityRepository
{
}
