<?php

namespace AppBundle\Repository;

/**
 * MarkPrecisionModeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MarkPrecisionModeRepository extends \Doctrine\ORM\EntityRepository
{
}
