<?php

namespace AppBundle\Repository;

/**
 * MarkRoundModeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MarkRoundModeRepository extends \Doctrine\ORM\EntityRepository
{
}
