<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Correction;
use Doctrine\ORM\EntityRepository;

/**
 * SectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SectionRepository extends EntityRepository
{
    function findWithAssignmentDependencies($evaluationId, $assignmentId)
    {
        $qb = $this->createQueryBuilder('s');
        $qb->select('s', 'ds')
            ->leftJoin('s.assignment_sections', 'ds', 'WITH', 'ds.assignment = :assignmentId')
            ->where('s.evaluation = :evaluationId')
            ->orderBy('s.order', 'ASC')
            ->setParameters(array(
                'evaluationId' => $evaluationId,
                'assignmentId' => $assignmentId
            ));
        $query = $qb->getQuery();
        $results = $query->getResult();
        return $results;
    }

    /**
     * @param Correction $correction
     * @return array
     */
    function findWithCorrectionDependencies(Correction $correction)
    {
        $qb = $this->createQueryBuilder('s');
        $qb->select('s', 'c', 'cc', 'ds')
            ->innerJoin('s.criterias', 'c')
            ->leftJoin('c.correction_criterias', 'cc', 'WITH', 'cc.correction = :correctionId')
            ->leftJoin('s.assignment_sections', 'ds', 'WITH', 'ds.assignment = :assignmentId')
            ->where('s.evaluation = :evaluationId')
            ->addOrderBy('s.order', 'ASC')
            ->addOrderBy('c.order', 'ASC')
            ->setParameters(array(
                'evaluationId' => $correction->getAssignment()->getEvaluation()->getId(),
                'assignmentId' => $correction->getAssignment()->getId(),
                'correctionId' => $correction->getId()
            ));
        $query = $qb->getQuery();
        $results = $query->getResult();
        return $results;
    }

}
