<?php

namespace AppBundle\Repository;

/**
 * SubjectFileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubjectFileRepository extends \Doctrine\ORM\EntityRepository
{
}
