imports:
    - { resource: config.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: false

web_profiler:
    toolbar: false
    intercept_redirects: false

monolog:
    handlers:
        main:
            type: rotating_file
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            max_files: 10
            channels: [!event, !doctrine, !security]
        error:
            type: rotating_file
            path: "%kernel.logs_dir%/%kernel.environment%_error.log"
            level: error
            max_files: 10
            channels: [!event]
        security:
            type: rotating_file
            path: "%kernel.logs_dir%/%kernel.environment%_security.log"
            level: debug
            max_files: 10
            channels: [security]
        db:
            type: rotating_file
            path: "%kernel.logs_dir%/%kernel.environment%_db.log"
            level: debug
            max_files: 10
            channels: [doctrine]
        console:
            type:   console
            channels: [!event, !doctrine]
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type:   firephp
        #    level:  info
        #chromephp:
        #    type:   chromephp
        #    level:  info

#swiftmailer:
#    delivery_address: me@example.com
